### PR TITLE
Update singleton_args.py

### PR DESCRIPTION
**Pull request by TonyDiana**
GIL control threading

### CODE REVIEW

**Comment by mammo0** [comment]
Hello @TonyDiana,

I don't get your intention for this PR... What is the purpose?

**Comment by TonyDiana** [comment]
If you want to perform singleton in several threads, GIL will control that none of them is leading or lagging, and will provide all threads with the same object

**Comment by mammo0** [comment]
Ah ok, you want a thread-safe Singleton.
I'll have a closer look tomorrow.

**Comment by TonyDiana** [comment]
It's just a suggestion

**Comment by mammo0** [comment]
Please have a look at the current version `1.3` that I've just released.

There is now a thread-safe version of the `Singleton` and `SingletonArgs` meta classes.

Thank you for your idea. I will close this PR now, because I implemented it in a slightly different way. I hope this is Ok for you?
If not, feel free to reopen this PR again.

**Comment by TonyDiana** [comment]
PERFECT

**Pull request closed without merging**
