### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by TonyDiana**
Sorry, this

### CODE REVIEW

**Comment by mammo0** [comment]
> Sorry, this

At first I didn't get this. But after a look at your fork I found the `patch-2` branch. There you left a similar commit with this message:

> A very very simple suggestion, which allows you to use this package not installed in the python library. Allows you to use it downloaded. For example, I use it within ``std/terceros`` (standard libraries, third party packages). This allows it to work in any context.
>
> With all my respect

So you want to use this package without installing it through pip? Adding the base directory to the `PYTHONPATH` should also work. Have you tested this?

I don't know if this change to relative imports will have unintended side effects... Will check this tomorrow.

**Comment by TonyDiana** [comment]
My suggestion is that neither environment variables nor pip is needed, then it is downloaded and works embedded in the product itself, which is how I like to make my own libraries, without dependencies to remember environment variables, that's why I always use them relative , that is what I meant

**Comment by TonyDiana** [comment]
My suggestion is that neither environment variables nor pip is needed, then it is downloaded and works embedded in the product itself, which is how I like to make my own libraries, without dependencies to remember environment variables, that's why I always use them relative , that is what I meant

**Comment by TonyDiana** [comment]
My suggestion is that neither environment variables nor pip is needed, then
it is downloaded and works embedded in the product itself, which is how I
like to make my own libraries, without dependencies to remember environment
variables, that's why I always use them relative , that is what I meant

----------------------------------------------------------------------------
<https://www.tonydiana.es/>
Tony Diana
 Email:  ***@***.***
  https://www.tonydiana.es/ <https://www.tonydiana.es/>

**Comment by mammo0** [comment]
I had a look at the pros and cons of using absolute or relative imports. And I think that it doesn't matter for my simple libraries/packages.

So I decided to follow your suggestion and make them more portable.
Unfortunately you deleted your fork, so I couldn't merge directly. Therefore I will close this PR now. Have a look at the latest version `v1.3.1` that contain the changes.

Thank you for your support/ideas.

**Comment by TonyDiana** [comment]
Yes, I still do not clarify with GitHUB, very used to working alone, eh, thanks

**Pull request closed without merging**
